name: create_docs
 
# execute this workflow automatically when we push to master or dev
on:
  push:
    branches:
      - master
      - dev

jobs:
 
  build_docs_job:
    runs-on: ubuntu-latest
    container: debian:trixie-slim
 
    steps:
 
    - name: Prereqs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -x
        apt-get update
        apt-get install -y git
        git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
        git config --global --add safe.directory .
      shell: bash
 
    - name: Execute script to build documentation and update pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: "docs/build_docs.sh"
      shell: bash

