name: create_docs
 
# execute this workflow automatically when we push to master or dev
on:
  push:
    branches:
      - master
      - dev

jobs:
 
  build_docs_job:
    runs-on: ubuntu-latest

    steps:

    # 1. Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0      # full history
        ref: master         # start from master branch
        fetch-tags: true    # optional: fetch tags if needed

    # 2. Fetch all remote branches (so build_docs.sh can iterate)
    - name: Fetch all remote branches
      run: git fetch --all

    # 3. Set up Python 3.13
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    # 4. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt

    # 5. Build and push documentation
    - name: Execute script to build documentation and update pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Run your build_docs.sh script
        bash docs/build_docs.sh